# Generated by Django 6.0.2 on 2026-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline_to_apply',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_package',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
