# Generated by Django 6.0.2 on 2026-04-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_job_deadline_to_apply_job_salary_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='remarks',
            field=models.TextField(blank=True, help_text='Recruiter remarks or feedback', null=True),
        ),
    ]
