# Generated by Django 6.0.2 on 2026-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_application_remarks'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='eligible_branches',
            field=models.ManyToManyField(blank=True, to='students.branch'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='students.skill'),
        ),
    ]
