# Generated by Django 6.0.2 on 2026-05-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_remove_job_skills_required_job_eligible_branches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, default='Full-time', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='On-site', max_length=255, null=True),
        ),
    ]
