# Generated by Django 6.0.2 on 2026-05-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_job_employment_type_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='meeting_link',
            field=models.CharField(blank=True, help_text='Online meeting URL or physical venue location', max_length=255, null=True),
        ),
    ]
