# Generated by Django 6.0.2 on 2026-05-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0006_alter_interview_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In-Person')], default='ONLINE', max_length=20),
        ),
    ]
