# Generated by Django 6.0.2 on 2026-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_skills_studentprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='internships',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
