# Generated by Django 6.0.2 on 2026-05-10 11:09

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_companyprofile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size]),
        ),
    ]
